from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.backend.domain.user.entity import User


class UserRepository(Protocol):
    async def get_by_username(self, username: str) -> User: ...

    async def get_by_email(self, email: str) -> User: ...

    async def get_by_id(self, user_id: UUID) -> User: ...

    async def exists_email(self, email: str, user_id: UUID = None) -> bool: ...

    async def exists_username(self, username: str, user_id: UUID = None) -> bool: ...

    async def create(self, user: User) -> User: ...

    async def update(self, user: User) -> None: ...

    async def delete(self, user: User) -> None: ...

    async def list_all(self): ...

    async def list_by_ids(self, user_ids: list[UUID]) -> list[User]: ...