apiVersion: 1

policies:
  - orgId: 1
    receiver: Telegram Alerts
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s       # wait before sending the first alert in a group
    group_interval: 5m    # minimum time between batches for the same group
    repeat_interval: 4h   # re-notify if alert is still firing after this
