from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.backend.application.blog.dtos.list_blog_posts import ListBlogPostsFilters
from src.backend.domain.blog.entity import BlogPost, BlogTag
from src.backend.domain.blog.product_link import BlogProductLink


class BlogPostRepository(Protocol):

    async def get_by_id(self, post_id: UUID) -> BlogPost | None: ...

    async def get_by_slug(self, slug: str) -> BlogPost | None: ...

    async def slug_exists(self, slug: str, exclude_id: UUID | None = None) -> bool: ...

    async def list(self, filters: ListBlogPostsFilters) -> list[BlogPost]: ...

    async def count(self, filters: ListBlogPostsFilters) -> int: ...

    async def create(self, post: BlogPost) -> BlogPost: ...

    async def update(self, post: BlogPost) -> None: ...

    async def delete(self, post: BlogPost) -> None: ...

    async def get_tags(self, post_id: UUID) -> list[BlogTag]: ...

    async def add_tag(self, post_id: UUID, tag_id: UUID) -> None: ...

    async def remove_tag(self, post_id: UUID, tag_id: UUID) -> None: ...

    async def get_product_links(self, post_id: UUID) -> list[BlogProductLink]: ...

    async def add_product_link(self, link: BlogProductLink) -> BlogProductLink: ...

    async def remove_product_link(self, link_id: UUID) -> None: ...


class BlogTagRepository(Protocol):

    async def get_by_id(self, tag_id: UUID) -> BlogTag | None: ...

    async def get_by_slug(self, slug: str) -> BlogTag | None: ...

    async def slug_exists(self, slug: str, exclude_id: UUID | None = None) -> bool: ...

    async def list(self) -> list[BlogTag]: ...

    async def create(self, tag: BlogTag) -> BlogTag: ...

    async def update(self, tag: BlogTag) -> None: ...

    async def delete(self, tag: BlogTag) -> None: ...
