"""add_group_to_characteristics

Revision ID: de06aeaed17c
Revises: b8fad5b42210
Create Date: 2026-06-18 20:33:08.549717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de06aeaed17c'
down_revision: Union[str, Sequence[str], None] = 'b8fad5b42210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristics', sa.Column('group', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characteristics', 'group')
    # ### end Alembic commands ###
