from __future__ import annotations

from typing import Protocol
from uuid import UUID

from src.backend.application.item.dtos.list_items import ListItemsFilters
from src.backend.domain.item.characteristic import Characteristic
from src.backend.domain.item.entity import Item
from src.backend.domain.item.gallery import Gallery
from src.backend.domain.tag.entity import Tag


class ItemRepository(Protocol):

    async def get_by_id(self, item_id: UUID) -> Item | None: ...

    async def list(self, filters: ListItemsFilters) -> list[Item]: ...

    async def count(self, filters: ListItemsFilters) -> int: ...

    async def create(self, item: Item) -> Item: ...

    async def update(self, item: Item) -> None: ...

    async def delete(self, item: Item) -> None: ...

    async def get_tags(self, item_id: UUID) -> list[Tag]: ...

    async def add_tag(self, item_id: UUID, tag_id: UUID) -> None: ...

    async def remove_tag(self, item_id: UUID, tag_id: UUID) -> None: ...

    async def increment_view_count(self, item_id: UUID) -> None: ...


class CharacteristicRepository(Protocol):

    async def get_by_id(self, characteristic_id: UUID) -> Characteristic | None: ...

    async def list_by_item(self, item_id: UUID) -> list[Characteristic]: ...

    async def create(self, characteristic: Characteristic) -> Characteristic: ...

    async def update(self, characteristic: Characteristic) -> None: ...

    async def delete(self, characteristic: Characteristic) -> None: ...


class GalleryRepository(Protocol):

    async def get_by_id(self, gallery_id: UUID) -> Gallery | None: ...

    async def list_by_item(self, item_id: UUID) -> list[Gallery]: ...

    async def get_preview_keys(self, item_ids: list[UUID]) -> dict[UUID, str | None]: ...

    async def create(self, gallery: Gallery) -> Gallery: ...

    async def delete(self, gallery: Gallery) -> None: ...
